version: '3'

services: 

    vue:
        ports:
            - 3000:3000
        build: 
            context: ./frontend
            dockerfile: Dockerfile
        volumes: 
            - ./frontend:/app
            - /app/node_modules
        networks: 
            - fullstack
    
    flask:
        ports:
            - 5000:5000
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            -  ./backend:/src

networks: 
    fullstack:
        driver: bridge