version: '3'

services: 

    react:
        ports:
            - 3000:3000
        build: 
            context: ./frontend
            dockerfile: Dockerfile
        volumes: 
            - ./frontend:/app
            - /app/node_modules
        networks: 
            - fullstack
        depends_on: 
            - go 
    
    go:
        ports:
            - 8080:8080
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            -  ./backend:/src
        networks: 
            - fullstack
        depends_on: 
            - mysql-container
    
    mysql-container:
        image: mysql
        environment: 
            MYSQL_ROOT_PASSWORD: root 
            MYSQL_DATABASE: Awty_Portal 
        container_name: mysql_container
        ports:
            - 6000:6000
        volumes: 
            - database_mysql:/var/lib/mysql
            - ./backend:/src/db.sql
        networks: 
            - fullstack

volumes: 
    database_mysql:

networks: 
    fullstack:
        driver: bridge